[profile.default]
src = "src"
test = "test"
out = "out"
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
robinhood_testnet = "${ROBINHOOD_TESTNET_RPC_URL}"
robinhood_mainnet = "${ROBINHOOD_MAINNET_RPC_URL}"
